/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CanvasAccessMethod
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum AppMenuItem_CanvasAccessMethodEnum {

    // Get
    GET("Get"),
    // Post
    POST("Post");

    final String value;

    private AppMenuItem_CanvasAccessMethodEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AppMenuItem_CanvasAccessMethodEnum fromValue(String value) {
        for (AppMenuItem_CanvasAccessMethodEnum e : AppMenuItem_CanvasAccessMethodEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
