/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum AsyncApexJob_StatusEnum {

    // Aborted
    ABORTED("Aborted"),
    // Completed
    COMPLETED("Completed"),
    // Failed
    FAILED("Failed"),
    // Holding
    HOLDING("Holding"),
    // Preparing
    PREPARING("Preparing"),
    // Processing
    PROCESSING("Processing"),
    // Queued
    QUEUED("Queued");

    final String value;

    private AsyncApexJob_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AsyncApexJob_StatusEnum fromValue(String value) {
        for (AsyncApexJob_StatusEnum e : AsyncApexJob_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
