/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Format
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum AuraDefinition_FormatEnum {

    // CSS
    CSS("CSS"),
    // JS
    JS("JS"),
    // SVG
    SVG("SVG"),
    // TEMPLATE_CSS
    TEMPLATE_CSS("TEMPLATE_CSS"),
    // XML
    XML("XML");

    final String value;

    private AuraDefinition_FormatEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AuraDefinition_FormatEnum fromValue(String value) {
        for (AuraDefinition_FormatEnum e : AuraDefinition_FormatEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
