/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LoginType
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum AuthSession_LoginTypeEnum {

    ; // empty picklist!

    final String value;

    private AuthSession_LoginTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AuthSession_LoginTypeEnum fromValue(String value) {
        for (AuthSession_LoginTypeEnum e : AuthSession_LoginTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
