/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TableEnumOrId
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum BusinessProcess_TableEnumOrIdEnum {

    // Case
    CASE("Case"),
    // Lead
    LEAD("Lead"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // Solution
    SOLUTION("Solution");

    final String value;

    private BusinessProcess_TableEnumOrIdEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BusinessProcess_TableEnumOrIdEnum fromValue(String value) {
        for (BusinessProcess_TableEnumOrIdEnum e : BusinessProcess_TableEnumOrIdEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
