/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PinLength
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum ConnectedApplication_PinLengthEnum {

    // 4
    _4("4"),
    // 5
    _5("5"),
    // 6
    _6("6"),
    // 7
    _7("7"),
    // 8
    _8("8");

    final String value;

    private ConnectedApplication_PinLengthEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ConnectedApplication_PinLengthEnum fromValue(String value) {
        for (ConnectedApplication_PinLengthEnum e : ConnectedApplication_PinLengthEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
