/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject ContactCleanInfo
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("ContactCleanInfo")
public class ContactCleanInfo extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // ContactId
    private String ContactId;

    @JsonProperty("ContactId")
    public String getContactId() {
        return this.ContactId;
    }

    @JsonProperty("ContactId")
    public void setContactId(String ContactId) {
        this.ContactId = ContactId;
    }

    // LastMatchedDate
    private java.time.ZonedDateTime LastMatchedDate;

    @JsonProperty("LastMatchedDate")
    public java.time.ZonedDateTime getLastMatchedDate() {
        return this.LastMatchedDate;
    }

    @JsonProperty("LastMatchedDate")
    public void setLastMatchedDate(java.time.ZonedDateTime LastMatchedDate) {
        this.LastMatchedDate = LastMatchedDate;
    }

    // LastStatusChangedDate
    private java.time.ZonedDateTime LastStatusChangedDate;

    @JsonProperty("LastStatusChangedDate")
    public java.time.ZonedDateTime getLastStatusChangedDate() {
        return this.LastStatusChangedDate;
    }

    @JsonProperty("LastStatusChangedDate")
    public void setLastStatusChangedDate(java.time.ZonedDateTime LastStatusChangedDate) {
        this.LastStatusChangedDate = LastStatusChangedDate;
    }

    // LastStatusChangedById
    private String LastStatusChangedById;

    @JsonProperty("LastStatusChangedById")
    public String getLastStatusChangedById() {
        return this.LastStatusChangedById;
    }

    @JsonProperty("LastStatusChangedById")
    public void setLastStatusChangedById(String LastStatusChangedById) {
        this.LastStatusChangedById = LastStatusChangedById;
    }

    // IsInactive
    private Boolean IsInactive;

    @JsonProperty("IsInactive")
    public Boolean getIsInactive() {
        return this.IsInactive;
    }

    @JsonProperty("IsInactive")
    public void setIsInactive(Boolean IsInactive) {
        this.IsInactive = IsInactive;
    }

    // FirstName
    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    // LastName
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    // Email
    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    // Phone
    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    // Street
    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    // City
    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // PostalCode
    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    // Country
    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    // Latitude
    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    // Longitude
    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    // Address
    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    // Title
    private String Title;

    @JsonProperty("Title")
    public String getTitle() {
        return this.Title;
    }

    @JsonProperty("Title")
    public void setTitle(String Title) {
        this.Title = Title;
    }

    // ContactStatusDataDotCom
    @XStreamConverter(PicklistEnumConverter.class)
    private ContactCleanInfo_ContactStatusDataDotComEnum ContactStatusDataDotCom;

    @JsonProperty("ContactStatusDataDotCom")
    public ContactCleanInfo_ContactStatusDataDotComEnum getContactStatusDataDotCom() {
        return this.ContactStatusDataDotCom;
    }

    @JsonProperty("ContactStatusDataDotCom")
    public void setContactStatusDataDotCom(ContactCleanInfo_ContactStatusDataDotComEnum ContactStatusDataDotCom) {
        this.ContactStatusDataDotCom = ContactStatusDataDotCom;
    }

    // IsReviewedName
    private Boolean IsReviewedName;

    @JsonProperty("IsReviewedName")
    public Boolean getIsReviewedName() {
        return this.IsReviewedName;
    }

    @JsonProperty("IsReviewedName")
    public void setIsReviewedName(Boolean IsReviewedName) {
        this.IsReviewedName = IsReviewedName;
    }

    // IsReviewedEmail
    private Boolean IsReviewedEmail;

    @JsonProperty("IsReviewedEmail")
    public Boolean getIsReviewedEmail() {
        return this.IsReviewedEmail;
    }

    @JsonProperty("IsReviewedEmail")
    public void setIsReviewedEmail(Boolean IsReviewedEmail) {
        this.IsReviewedEmail = IsReviewedEmail;
    }

    // IsReviewedPhone
    private Boolean IsReviewedPhone;

    @JsonProperty("IsReviewedPhone")
    public Boolean getIsReviewedPhone() {
        return this.IsReviewedPhone;
    }

    @JsonProperty("IsReviewedPhone")
    public void setIsReviewedPhone(Boolean IsReviewedPhone) {
        this.IsReviewedPhone = IsReviewedPhone;
    }

    // IsReviewedAddress
    private Boolean IsReviewedAddress;

    @JsonProperty("IsReviewedAddress")
    public Boolean getIsReviewedAddress() {
        return this.IsReviewedAddress;
    }

    @JsonProperty("IsReviewedAddress")
    public void setIsReviewedAddress(Boolean IsReviewedAddress) {
        this.IsReviewedAddress = IsReviewedAddress;
    }

    // IsReviewedTitle
    private Boolean IsReviewedTitle;

    @JsonProperty("IsReviewedTitle")
    public Boolean getIsReviewedTitle() {
        return this.IsReviewedTitle;
    }

    @JsonProperty("IsReviewedTitle")
    public void setIsReviewedTitle(Boolean IsReviewedTitle) {
        this.IsReviewedTitle = IsReviewedTitle;
    }

    // IsDifferentFirstName
    private Boolean IsDifferentFirstName;

    @JsonProperty("IsDifferentFirstName")
    public Boolean getIsDifferentFirstName() {
        return this.IsDifferentFirstName;
    }

    @JsonProperty("IsDifferentFirstName")
    public void setIsDifferentFirstName(Boolean IsDifferentFirstName) {
        this.IsDifferentFirstName = IsDifferentFirstName;
    }

    // IsDifferentLastName
    private Boolean IsDifferentLastName;

    @JsonProperty("IsDifferentLastName")
    public Boolean getIsDifferentLastName() {
        return this.IsDifferentLastName;
    }

    @JsonProperty("IsDifferentLastName")
    public void setIsDifferentLastName(Boolean IsDifferentLastName) {
        this.IsDifferentLastName = IsDifferentLastName;
    }

    // IsDifferentEmail
    private Boolean IsDifferentEmail;

    @JsonProperty("IsDifferentEmail")
    public Boolean getIsDifferentEmail() {
        return this.IsDifferentEmail;
    }

    @JsonProperty("IsDifferentEmail")
    public void setIsDifferentEmail(Boolean IsDifferentEmail) {
        this.IsDifferentEmail = IsDifferentEmail;
    }

    // IsDifferentPhone
    private Boolean IsDifferentPhone;

    @JsonProperty("IsDifferentPhone")
    public Boolean getIsDifferentPhone() {
        return this.IsDifferentPhone;
    }

    @JsonProperty("IsDifferentPhone")
    public void setIsDifferentPhone(Boolean IsDifferentPhone) {
        this.IsDifferentPhone = IsDifferentPhone;
    }

    // IsDifferentStreet
    private Boolean IsDifferentStreet;

    @JsonProperty("IsDifferentStreet")
    public Boolean getIsDifferentStreet() {
        return this.IsDifferentStreet;
    }

    @JsonProperty("IsDifferentStreet")
    public void setIsDifferentStreet(Boolean IsDifferentStreet) {
        this.IsDifferentStreet = IsDifferentStreet;
    }

    // IsDifferentCity
    private Boolean IsDifferentCity;

    @JsonProperty("IsDifferentCity")
    public Boolean getIsDifferentCity() {
        return this.IsDifferentCity;
    }

    @JsonProperty("IsDifferentCity")
    public void setIsDifferentCity(Boolean IsDifferentCity) {
        this.IsDifferentCity = IsDifferentCity;
    }

    // IsDifferentState
    private Boolean IsDifferentState;

    @JsonProperty("IsDifferentState")
    public Boolean getIsDifferentState() {
        return this.IsDifferentState;
    }

    @JsonProperty("IsDifferentState")
    public void setIsDifferentState(Boolean IsDifferentState) {
        this.IsDifferentState = IsDifferentState;
    }

    // IsDifferentPostalCode
    private Boolean IsDifferentPostalCode;

    @JsonProperty("IsDifferentPostalCode")
    public Boolean getIsDifferentPostalCode() {
        return this.IsDifferentPostalCode;
    }

    @JsonProperty("IsDifferentPostalCode")
    public void setIsDifferentPostalCode(Boolean IsDifferentPostalCode) {
        this.IsDifferentPostalCode = IsDifferentPostalCode;
    }

    // IsDifferentCountry
    private Boolean IsDifferentCountry;

    @JsonProperty("IsDifferentCountry")
    public Boolean getIsDifferentCountry() {
        return this.IsDifferentCountry;
    }

    @JsonProperty("IsDifferentCountry")
    public void setIsDifferentCountry(Boolean IsDifferentCountry) {
        this.IsDifferentCountry = IsDifferentCountry;
    }

    // IsDifferentTitle
    private Boolean IsDifferentTitle;

    @JsonProperty("IsDifferentTitle")
    public Boolean getIsDifferentTitle() {
        return this.IsDifferentTitle;
    }

    @JsonProperty("IsDifferentTitle")
    public void setIsDifferentTitle(Boolean IsDifferentTitle) {
        this.IsDifferentTitle = IsDifferentTitle;
    }

    // IsDifferentStateCode
    private Boolean IsDifferentStateCode;

    @JsonProperty("IsDifferentStateCode")
    public Boolean getIsDifferentStateCode() {
        return this.IsDifferentStateCode;
    }

    @JsonProperty("IsDifferentStateCode")
    public void setIsDifferentStateCode(Boolean IsDifferentStateCode) {
        this.IsDifferentStateCode = IsDifferentStateCode;
    }

    // IsDifferentCountryCode
    private Boolean IsDifferentCountryCode;

    @JsonProperty("IsDifferentCountryCode")
    public Boolean getIsDifferentCountryCode() {
        return this.IsDifferentCountryCode;
    }

    @JsonProperty("IsDifferentCountryCode")
    public void setIsDifferentCountryCode(Boolean IsDifferentCountryCode) {
        this.IsDifferentCountryCode = IsDifferentCountryCode;
    }

    // CleanedByJob
    private Boolean CleanedByJob;

    @JsonProperty("CleanedByJob")
    public Boolean getCleanedByJob() {
        return this.CleanedByJob;
    }

    @JsonProperty("CleanedByJob")
    public void setCleanedByJob(Boolean CleanedByJob) {
        this.CleanedByJob = CleanedByJob;
    }

    // CleanedByUser
    private Boolean CleanedByUser;

    @JsonProperty("CleanedByUser")
    public Boolean getCleanedByUser() {
        return this.CleanedByUser;
    }

    @JsonProperty("CleanedByUser")
    public void setCleanedByUser(Boolean CleanedByUser) {
        this.CleanedByUser = CleanedByUser;
    }

    // IsFlaggedWrongName
    private Boolean IsFlaggedWrongName;

    @JsonProperty("IsFlaggedWrongName")
    public Boolean getIsFlaggedWrongName() {
        return this.IsFlaggedWrongName;
    }

    @JsonProperty("IsFlaggedWrongName")
    public void setIsFlaggedWrongName(Boolean IsFlaggedWrongName) {
        this.IsFlaggedWrongName = IsFlaggedWrongName;
    }

    // IsFlaggedWrongEmail
    private Boolean IsFlaggedWrongEmail;

    @JsonProperty("IsFlaggedWrongEmail")
    public Boolean getIsFlaggedWrongEmail() {
        return this.IsFlaggedWrongEmail;
    }

    @JsonProperty("IsFlaggedWrongEmail")
    public void setIsFlaggedWrongEmail(Boolean IsFlaggedWrongEmail) {
        this.IsFlaggedWrongEmail = IsFlaggedWrongEmail;
    }

    // IsFlaggedWrongPhone
    private Boolean IsFlaggedWrongPhone;

    @JsonProperty("IsFlaggedWrongPhone")
    public Boolean getIsFlaggedWrongPhone() {
        return this.IsFlaggedWrongPhone;
    }

    @JsonProperty("IsFlaggedWrongPhone")
    public void setIsFlaggedWrongPhone(Boolean IsFlaggedWrongPhone) {
        this.IsFlaggedWrongPhone = IsFlaggedWrongPhone;
    }

    // IsFlaggedWrongAddress
    private Boolean IsFlaggedWrongAddress;

    @JsonProperty("IsFlaggedWrongAddress")
    public Boolean getIsFlaggedWrongAddress() {
        return this.IsFlaggedWrongAddress;
    }

    @JsonProperty("IsFlaggedWrongAddress")
    public void setIsFlaggedWrongAddress(Boolean IsFlaggedWrongAddress) {
        this.IsFlaggedWrongAddress = IsFlaggedWrongAddress;
    }

    // IsFlaggedWrongTitle
    private Boolean IsFlaggedWrongTitle;

    @JsonProperty("IsFlaggedWrongTitle")
    public Boolean getIsFlaggedWrongTitle() {
        return this.IsFlaggedWrongTitle;
    }

    @JsonProperty("IsFlaggedWrongTitle")
    public void setIsFlaggedWrongTitle(Boolean IsFlaggedWrongTitle) {
        this.IsFlaggedWrongTitle = IsFlaggedWrongTitle;
    }

    // DataDotComId
    private String DataDotComId;

    @JsonProperty("DataDotComId")
    public String getDataDotComId() {
        return this.DataDotComId;
    }

    @JsonProperty("DataDotComId")
    public void setDataDotComId(String DataDotComId) {
        this.DataDotComId = DataDotComId;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Contact Clean Info ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("Name", "Contact Clean Info Name", "string", "xsd:string", 255, false, false, true, false, false, false, true);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("ContactId", "Contact ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("LastMatchedDate", "Last Matched Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("LastStatusChangedDate", "Last Status Changed Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("LastStatusChangedById", "User ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("IsInactive", "Contact Status in Salesforce", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("FirstName", "First Name", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("LastName", "Last Name", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("Email", "Email", "email", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("Phone", "Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("Street", "Street", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("State", "State", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("PostalCode", "Zip", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("Latitude", "Latitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("Longitude", "Longitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("Address", "Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("Title", "Title", "string", "xsd:string", 128, false, true, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("ContactStatusDataDotCom", "Contact Status per Data.com", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("IsReviewedName", "Name is Reviewed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("IsReviewedEmail", "Email is Reviewed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("IsReviewedPhone", "Phone is Reviewed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("IsReviewedAddress", "Address is Reviewed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("IsReviewedTitle", "Title is Reviewed", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("IsDifferentFirstName", "First Name is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("IsDifferentLastName", "Last Name is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("IsDifferentEmail", "Email is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("IsDifferentPhone", "Phone is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("IsDifferentStreet", "Street is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("IsDifferentCity", "City is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("IsDifferentState", "State is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("IsDifferentPostalCode", "ZIP is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("IsDifferentCountry", "Country is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("IsDifferentTitle", "Title is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("IsDifferentStateCode", "State Code is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("IsDifferentCountryCode", "Country Code is Different", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("CleanedByJob", "Cleaned by Job", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("CleanedByUser", "Cleaned by User", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField46);
        final SObjectField sObjectField47 = createField("IsFlaggedWrongName", "Name is Flagged Wrong", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField47);
        final SObjectField sObjectField48 = createField("IsFlaggedWrongEmail", "Email is Flagged Wrong", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField48);
        final SObjectField sObjectField49 = createField("IsFlaggedWrongPhone", "Phone is Flagged Wrong", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField49);
        final SObjectField sObjectField50 = createField("IsFlaggedWrongAddress", "Address is Flagged Wrong", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField50);
        final SObjectField sObjectField51 = createField("IsFlaggedWrongTitle", "Title is Flagged Wrong", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField51);
        final SObjectField sObjectField52 = createField("DataDotComId", "Data.com ID", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField52);

        description.setLabelPlural("Contact Clean Info");
        description.setLabel("Contact Clean Info");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/ContactCleanInfo/describe");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/ContactCleanInfo");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/ContactCleanInfo/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("ContactCleanInfo");

        return description;
    }
}
