/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BackgroundDirection
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Dashboard_BackgroundDirectionEnum {

    // Diagonal
    DIAGONAL("Diagonal"),
    // LeftToRight
    LEFTTORIGHT("LeftToRight"),
    // TopToBottom
    TOPTOBOTTOM("TopToBottom");

    final String value;

    private Dashboard_BackgroundDirectionEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Dashboard_BackgroundDirectionEnum fromValue(String value) {
        for (Dashboard_BackgroundDirectionEnum e : Dashboard_BackgroundDirectionEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
