/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject DatacloudOwnedEntity
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("DatacloudOwnedEntity")
public class DatacloudOwnedEntity extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // DataDotComKey
    private String DataDotComKey;

    @JsonProperty("DataDotComKey")
    public String getDataDotComKey() {
        return this.DataDotComKey;
    }

    @JsonProperty("DataDotComKey")
    public void setDataDotComKey(String DataDotComKey) {
        this.DataDotComKey = DataDotComKey;
    }

    // DatacloudEntityType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudOwnedEntity_DatacloudEntityTypeEnum DatacloudEntityType;

    @JsonProperty("DatacloudEntityType")
    public DatacloudOwnedEntity_DatacloudEntityTypeEnum getDatacloudEntityType() {
        return this.DatacloudEntityType;
    }

    @JsonProperty("DatacloudEntityType")
    public void setDatacloudEntityType(DatacloudOwnedEntity_DatacloudEntityTypeEnum DatacloudEntityType) {
        this.DatacloudEntityType = DatacloudEntityType;
    }

    // UserId
    private String UserId;

    @JsonProperty("UserId")
    public String getUserId() {
        return this.UserId;
    }

    @JsonProperty("UserId")
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    // PurchaseUsageId
    private String PurchaseUsageId;

    @JsonProperty("PurchaseUsageId")
    public String getPurchaseUsageId() {
        return this.PurchaseUsageId;
    }

    @JsonProperty("PurchaseUsageId")
    public void setPurchaseUsageId(String PurchaseUsageId) {
        this.PurchaseUsageId = PurchaseUsageId;
    }

    // PurchaseType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudOwnedEntity_PurchaseTypeEnum PurchaseType;

    @JsonProperty("PurchaseType")
    public DatacloudOwnedEntity_PurchaseTypeEnum getPurchaseType() {
        return this.PurchaseType;
    }

    @JsonProperty("PurchaseType")
    public void setPurchaseType(DatacloudOwnedEntity_PurchaseTypeEnum PurchaseType) {
        this.PurchaseType = PurchaseType;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Data.com Owned Entity ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("Name", "Description", "string", "xsd:string", 255, false, false, true, false, false, false, true);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("DataDotComKey", "Data.com key", "string", "xsd:string", 25, false, false, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("DatacloudEntityType", "Data.com Object Type", "picklist", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("UserId", "User ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("PurchaseUsageId", "Data.com Usage ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("PurchaseType", "Data.com Purchase Type", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);

        description.setLabelPlural("Data.com Owned Entity");
        description.setLabel("Data.com Owned Entity");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/DatacloudOwnedEntity/describe");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/DatacloudOwnedEntity");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/DatacloudOwnedEntity/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("DatacloudOwnedEntity");

        return description;
    }
}
