/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject DatacloudPurchaseUsage
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("DatacloudPurchaseUsage")
public class DatacloudPurchaseUsage extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // UserId
    private String UserId;

    @JsonProperty("UserId")
    public String getUserId() {
        return this.UserId;
    }

    @JsonProperty("UserId")
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    // UserType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudPurchaseUsage_UserTypeEnum UserType;

    @JsonProperty("UserType")
    public DatacloudPurchaseUsage_UserTypeEnum getUserType() {
        return this.UserType;
    }

    @JsonProperty("UserType")
    public void setUserType(DatacloudPurchaseUsage_UserTypeEnum UserType) {
        this.UserType = UserType;
    }

    // PurchaseType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudPurchaseUsage_PurchaseTypeEnum PurchaseType;

    @JsonProperty("PurchaseType")
    public DatacloudPurchaseUsage_PurchaseTypeEnum getPurchaseType() {
        return this.PurchaseType;
    }

    @JsonProperty("PurchaseType")
    public void setPurchaseType(DatacloudPurchaseUsage_PurchaseTypeEnum PurchaseType) {
        this.PurchaseType = PurchaseType;
    }

    // DatacloudEntityType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudPurchaseUsage_DatacloudEntityTypeEnum DatacloudEntityType;

    @JsonProperty("DatacloudEntityType")
    public DatacloudPurchaseUsage_DatacloudEntityTypeEnum getDatacloudEntityType() {
        return this.DatacloudEntityType;
    }

    @JsonProperty("DatacloudEntityType")
    public void setDatacloudEntityType(DatacloudPurchaseUsage_DatacloudEntityTypeEnum DatacloudEntityType) {
        this.DatacloudEntityType = DatacloudEntityType;
    }

    // Usage
    private Double Usage;

    @JsonProperty("Usage")
    public Double getUsage() {
        return this.Usage;
    }

    @JsonProperty("Usage")
    public void setUsage(Double Usage) {
        this.Usage = Usage;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Data.com Usage ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("Name", "Sequence ID", "string", "xsd:string", 255, false, false, true, false, false, false, true);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("UserId", "User ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("UserType", "Data.com Usage Type", "picklist", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("PurchaseType", "Data.com Purchase Type", "picklist", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("DatacloudEntityType", "Data.com Object Type", "picklist", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("Usage", "Purchase Count", "double", "xsd:double", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("Description", "Description", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);

        description.setLabelPlural("Data.com Usage");
        description.setLabel("Data.com Usage");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/DatacloudPurchaseUsage/describe");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/DatacloudPurchaseUsage");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/DatacloudPurchaseUsage/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("DatacloudPurchaseUsage");

        return description;
    }
}
