/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;

import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject EmailStatus
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("EmailStatus")
public class EmailStatus extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // TaskId
    private String TaskId;

    @JsonProperty("TaskId")
    public String getTaskId() {
        return this.TaskId;
    }

    @JsonProperty("TaskId")
    public void setTaskId(String TaskId) {
        this.TaskId = TaskId;
    }

    // WhoId
    private String WhoId;

    @JsonProperty("WhoId")
    public String getWhoId() {
        return this.WhoId;
    }

    @JsonProperty("WhoId")
    public void setWhoId(String WhoId) {
        this.WhoId = WhoId;
    }

    // TimesOpened
    private Integer TimesOpened;

    @JsonProperty("TimesOpened")
    public Integer getTimesOpened() {
        return this.TimesOpened;
    }

    @JsonProperty("TimesOpened")
    public void setTimesOpened(Integer TimesOpened) {
        this.TimesOpened = TimesOpened;
    }

    // FirstOpenDate
    private java.time.ZonedDateTime FirstOpenDate;

    @JsonProperty("FirstOpenDate")
    public java.time.ZonedDateTime getFirstOpenDate() {
        return this.FirstOpenDate;
    }

    @JsonProperty("FirstOpenDate")
    public void setFirstOpenDate(java.time.ZonedDateTime FirstOpenDate) {
        this.FirstOpenDate = FirstOpenDate;
    }

    // LastOpenDate
    private java.time.ZonedDateTime LastOpenDate;

    @JsonProperty("LastOpenDate")
    public java.time.ZonedDateTime getLastOpenDate() {
        return this.LastOpenDate;
    }

    @JsonProperty("LastOpenDate")
    public void setLastOpenDate(java.time.ZonedDateTime LastOpenDate) {
        this.LastOpenDate = LastOpenDate;
    }

    // EmailTemplateName
    private String EmailTemplateName;

    @JsonProperty("EmailTemplateName")
    public String getEmailTemplateName() {
        return this.EmailTemplateName;
    }

    @JsonProperty("EmailTemplateName")
    public void setEmailTemplateName(String EmailTemplateName) {
        this.EmailTemplateName = EmailTemplateName;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Email Status ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("TaskId", "Activity ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("WhoId", "Name ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("TimesOpened", "# Times Opened", "int", "xsd:int", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("FirstOpenDate", "Date Opened", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("LastOpenDate", "Last Opened", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("EmailTemplateName", "Email Template Name", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);

        description.setLabelPlural("Email Status");
        description.setLabel("Email Status");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/EmailStatus/describe");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/EmailStatus");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/EmailStatus/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("EmailStatus");

        return description;
    }
}
