/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist MatchingMethod
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum MatchingRuleItem_MatchingMethodEnum {

    // City
    CITY("City"),
    // CompanyName
    COMPANYNAME("CompanyName"),
    // Exact
    EXACT("Exact"),
    // FirstName
    FIRSTNAME("FirstName"),
    // LastName
    LASTNAME("LastName"),
    // Phone
    PHONE("Phone"),
    // Street
    STREET("Street"),
    // Title
    TITLE("Title"),
    // Zip
    ZIP("Zip");

    final String value;

    private MatchingRuleItem_MatchingMethodEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static MatchingRuleItem_MatchingMethodEnum fromValue(String value) {
        for (MatchingRuleItem_MatchingMethodEnum e : MatchingRuleItem_MatchingMethodEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
