/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Organization
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("Organization")
public class Organization extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // Division
    private String Division;

    @JsonProperty("Division")
    public String getDivision() {
        return this.Division;
    }

    @JsonProperty("Division")
    public void setDivision(String Division) {
        this.Division = Division;
    }

    // Street
    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    // City
    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // PostalCode
    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    // Country
    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    // Latitude
    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    // Longitude
    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    // Address
    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    // Phone
    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    // Fax
    private String Fax;

    @JsonProperty("Fax")
    public String getFax() {
        return this.Fax;
    }

    @JsonProperty("Fax")
    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    // PrimaryContact
    private String PrimaryContact;

    @JsonProperty("PrimaryContact")
    public String getPrimaryContact() {
        return this.PrimaryContact;
    }

    @JsonProperty("PrimaryContact")
    public void setPrimaryContact(String PrimaryContact) {
        this.PrimaryContact = PrimaryContact;
    }

    // DefaultLocaleSidKey
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultLocaleSidKeyEnum DefaultLocaleSidKey;

    @JsonProperty("DefaultLocaleSidKey")
    public Organization_DefaultLocaleSidKeyEnum getDefaultLocaleSidKey() {
        return this.DefaultLocaleSidKey;
    }

    @JsonProperty("DefaultLocaleSidKey")
    public void setDefaultLocaleSidKey(Organization_DefaultLocaleSidKeyEnum DefaultLocaleSidKey) {
        this.DefaultLocaleSidKey = DefaultLocaleSidKey;
    }

    // LanguageLocaleKey
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_LanguageLocaleKeyEnum LanguageLocaleKey;

    @JsonProperty("LanguageLocaleKey")
    public Organization_LanguageLocaleKeyEnum getLanguageLocaleKey() {
        return this.LanguageLocaleKey;
    }

    @JsonProperty("LanguageLocaleKey")
    public void setLanguageLocaleKey(Organization_LanguageLocaleKeyEnum LanguageLocaleKey) {
        this.LanguageLocaleKey = LanguageLocaleKey;
    }

    // ReceivesInfoEmails
    private Boolean ReceivesInfoEmails;

    @JsonProperty("ReceivesInfoEmails")
    public Boolean getReceivesInfoEmails() {
        return this.ReceivesInfoEmails;
    }

    @JsonProperty("ReceivesInfoEmails")
    public void setReceivesInfoEmails(Boolean ReceivesInfoEmails) {
        this.ReceivesInfoEmails = ReceivesInfoEmails;
    }

    // ReceivesAdminInfoEmails
    private Boolean ReceivesAdminInfoEmails;

    @JsonProperty("ReceivesAdminInfoEmails")
    public Boolean getReceivesAdminInfoEmails() {
        return this.ReceivesAdminInfoEmails;
    }

    @JsonProperty("ReceivesAdminInfoEmails")
    public void setReceivesAdminInfoEmails(Boolean ReceivesAdminInfoEmails) {
        this.ReceivesAdminInfoEmails = ReceivesAdminInfoEmails;
    }

    // PreferencesRequireOpportunityProducts
    private Boolean PreferencesRequireOpportunityProducts;

    @JsonProperty("PreferencesRequireOpportunityProducts")
    public Boolean getPreferencesRequireOpportunityProducts() {
        return this.PreferencesRequireOpportunityProducts;
    }

    @JsonProperty("PreferencesRequireOpportunityProducts")
    public void setPreferencesRequireOpportunityProducts(Boolean PreferencesRequireOpportunityProducts) {
        this.PreferencesRequireOpportunityProducts = PreferencesRequireOpportunityProducts;
    }

    // PreferencesTransactionSecurityPolicy
    private Boolean PreferencesTransactionSecurityPolicy;

    @JsonProperty("PreferencesTransactionSecurityPolicy")
    public Boolean getPreferencesTransactionSecurityPolicy() {
        return this.PreferencesTransactionSecurityPolicy;
    }

    @JsonProperty("PreferencesTransactionSecurityPolicy")
    public void setPreferencesTransactionSecurityPolicy(Boolean PreferencesTransactionSecurityPolicy) {
        this.PreferencesTransactionSecurityPolicy = PreferencesTransactionSecurityPolicy;
    }

    // PreferencesTerminateOldestSession
    private Boolean PreferencesTerminateOldestSession;

    @JsonProperty("PreferencesTerminateOldestSession")
    public Boolean getPreferencesTerminateOldestSession() {
        return this.PreferencesTerminateOldestSession;
    }

    @JsonProperty("PreferencesTerminateOldestSession")
    public void setPreferencesTerminateOldestSession(Boolean PreferencesTerminateOldestSession) {
        this.PreferencesTerminateOldestSession = PreferencesTerminateOldestSession;
    }

    // FiscalYearStartMonth
    private Integer FiscalYearStartMonth;

    @JsonProperty("FiscalYearStartMonth")
    public Integer getFiscalYearStartMonth() {
        return this.FiscalYearStartMonth;
    }

    @JsonProperty("FiscalYearStartMonth")
    public void setFiscalYearStartMonth(Integer FiscalYearStartMonth) {
        this.FiscalYearStartMonth = FiscalYearStartMonth;
    }

    // UsesStartDateAsFiscalYearName
    private Boolean UsesStartDateAsFiscalYearName;

    @JsonProperty("UsesStartDateAsFiscalYearName")
    public Boolean getUsesStartDateAsFiscalYearName() {
        return this.UsesStartDateAsFiscalYearName;
    }

    @JsonProperty("UsesStartDateAsFiscalYearName")
    public void setUsesStartDateAsFiscalYearName(Boolean UsesStartDateAsFiscalYearName) {
        this.UsesStartDateAsFiscalYearName = UsesStartDateAsFiscalYearName;
    }

    // DefaultAccountAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultAccountAccessEnum DefaultAccountAccess;

    @JsonProperty("DefaultAccountAccess")
    public Organization_DefaultAccountAccessEnum getDefaultAccountAccess() {
        return this.DefaultAccountAccess;
    }

    @JsonProperty("DefaultAccountAccess")
    public void setDefaultAccountAccess(Organization_DefaultAccountAccessEnum DefaultAccountAccess) {
        this.DefaultAccountAccess = DefaultAccountAccess;
    }

    // DefaultContactAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultContactAccessEnum DefaultContactAccess;

    @JsonProperty("DefaultContactAccess")
    public Organization_DefaultContactAccessEnum getDefaultContactAccess() {
        return this.DefaultContactAccess;
    }

    @JsonProperty("DefaultContactAccess")
    public void setDefaultContactAccess(Organization_DefaultContactAccessEnum DefaultContactAccess) {
        this.DefaultContactAccess = DefaultContactAccess;
    }

    // DefaultOpportunityAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultOpportunityAccessEnum DefaultOpportunityAccess;

    @JsonProperty("DefaultOpportunityAccess")
    public Organization_DefaultOpportunityAccessEnum getDefaultOpportunityAccess() {
        return this.DefaultOpportunityAccess;
    }

    @JsonProperty("DefaultOpportunityAccess")
    public void setDefaultOpportunityAccess(Organization_DefaultOpportunityAccessEnum DefaultOpportunityAccess) {
        this.DefaultOpportunityAccess = DefaultOpportunityAccess;
    }

    // DefaultLeadAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultLeadAccessEnum DefaultLeadAccess;

    @JsonProperty("DefaultLeadAccess")
    public Organization_DefaultLeadAccessEnum getDefaultLeadAccess() {
        return this.DefaultLeadAccess;
    }

    @JsonProperty("DefaultLeadAccess")
    public void setDefaultLeadAccess(Organization_DefaultLeadAccessEnum DefaultLeadAccess) {
        this.DefaultLeadAccess = DefaultLeadAccess;
    }

    // DefaultCaseAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultCaseAccessEnum DefaultCaseAccess;

    @JsonProperty("DefaultCaseAccess")
    public Organization_DefaultCaseAccessEnum getDefaultCaseAccess() {
        return this.DefaultCaseAccess;
    }

    @JsonProperty("DefaultCaseAccess")
    public void setDefaultCaseAccess(Organization_DefaultCaseAccessEnum DefaultCaseAccess) {
        this.DefaultCaseAccess = DefaultCaseAccess;
    }

    // DefaultCalendarAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultCalendarAccessEnum DefaultCalendarAccess;

    @JsonProperty("DefaultCalendarAccess")
    public Organization_DefaultCalendarAccessEnum getDefaultCalendarAccess() {
        return this.DefaultCalendarAccess;
    }

    @JsonProperty("DefaultCalendarAccess")
    public void setDefaultCalendarAccess(Organization_DefaultCalendarAccessEnum DefaultCalendarAccess) {
        this.DefaultCalendarAccess = DefaultCalendarAccess;
    }

    // DefaultPricebookAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultPricebookAccessEnum DefaultPricebookAccess;

    @JsonProperty("DefaultPricebookAccess")
    public Organization_DefaultPricebookAccessEnum getDefaultPricebookAccess() {
        return this.DefaultPricebookAccess;
    }

    @JsonProperty("DefaultPricebookAccess")
    public void setDefaultPricebookAccess(Organization_DefaultPricebookAccessEnum DefaultPricebookAccess) {
        this.DefaultPricebookAccess = DefaultPricebookAccess;
    }

    // DefaultCampaignAccess
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_DefaultCampaignAccessEnum DefaultCampaignAccess;

    @JsonProperty("DefaultCampaignAccess")
    public Organization_DefaultCampaignAccessEnum getDefaultCampaignAccess() {
        return this.DefaultCampaignAccess;
    }

    @JsonProperty("DefaultCampaignAccess")
    public void setDefaultCampaignAccess(Organization_DefaultCampaignAccessEnum DefaultCampaignAccess) {
        this.DefaultCampaignAccess = DefaultCampaignAccess;
    }

    // ComplianceBccEmail
    private String ComplianceBccEmail;

    @JsonProperty("ComplianceBccEmail")
    public String getComplianceBccEmail() {
        return this.ComplianceBccEmail;
    }

    @JsonProperty("ComplianceBccEmail")
    public void setComplianceBccEmail(String ComplianceBccEmail) {
        this.ComplianceBccEmail = ComplianceBccEmail;
    }

    // UiSkin
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_UiSkinEnum UiSkin;

    @JsonProperty("UiSkin")
    public Organization_UiSkinEnum getUiSkin() {
        return this.UiSkin;
    }

    @JsonProperty("UiSkin")
    public void setUiSkin(Organization_UiSkinEnum UiSkin) {
        this.UiSkin = UiSkin;
    }

    // SignupCountryIsoCode
    private String SignupCountryIsoCode;

    @JsonProperty("SignupCountryIsoCode")
    public String getSignupCountryIsoCode() {
        return this.SignupCountryIsoCode;
    }

    @JsonProperty("SignupCountryIsoCode")
    public void setSignupCountryIsoCode(String SignupCountryIsoCode) {
        this.SignupCountryIsoCode = SignupCountryIsoCode;
    }

    // TrialExpirationDate
    private java.time.ZonedDateTime TrialExpirationDate;

    @JsonProperty("TrialExpirationDate")
    public java.time.ZonedDateTime getTrialExpirationDate() {
        return this.TrialExpirationDate;
    }

    @JsonProperty("TrialExpirationDate")
    public void setTrialExpirationDate(java.time.ZonedDateTime TrialExpirationDate) {
        this.TrialExpirationDate = TrialExpirationDate;
    }

    // OrganizationType
    @XStreamConverter(PicklistEnumConverter.class)
    private Organization_OrganizationTypeEnum OrganizationType;

    @JsonProperty("OrganizationType")
    public Organization_OrganizationTypeEnum getOrganizationType() {
        return this.OrganizationType;
    }

    @JsonProperty("OrganizationType")
    public void setOrganizationType(Organization_OrganizationTypeEnum OrganizationType) {
        this.OrganizationType = OrganizationType;
    }

    // InstanceName
    private String InstanceName;

    @JsonProperty("InstanceName")
    public String getInstanceName() {
        return this.InstanceName;
    }

    @JsonProperty("InstanceName")
    public void setInstanceName(String InstanceName) {
        this.InstanceName = InstanceName;
    }

    // IsSandbox
    private Boolean IsSandbox;

    @JsonProperty("IsSandbox")
    public Boolean getIsSandbox() {
        return this.IsSandbox;
    }

    @JsonProperty("IsSandbox")
    public void setIsSandbox(Boolean IsSandbox) {
        this.IsSandbox = IsSandbox;
    }

    // WebToCaseDefaultOrigin
    private String WebToCaseDefaultOrigin;

    @JsonProperty("WebToCaseDefaultOrigin")
    public String getWebToCaseDefaultOrigin() {
        return this.WebToCaseDefaultOrigin;
    }

    @JsonProperty("WebToCaseDefaultOrigin")
    public void setWebToCaseDefaultOrigin(String WebToCaseDefaultOrigin) {
        this.WebToCaseDefaultOrigin = WebToCaseDefaultOrigin;
    }

    // MonthlyPageViewsUsed
    private Integer MonthlyPageViewsUsed;

    @JsonProperty("MonthlyPageViewsUsed")
    public Integer getMonthlyPageViewsUsed() {
        return this.MonthlyPageViewsUsed;
    }

    @JsonProperty("MonthlyPageViewsUsed")
    public void setMonthlyPageViewsUsed(Integer MonthlyPageViewsUsed) {
        this.MonthlyPageViewsUsed = MonthlyPageViewsUsed;
    }

    // MonthlyPageViewsEntitlement
    private Integer MonthlyPageViewsEntitlement;

    @JsonProperty("MonthlyPageViewsEntitlement")
    public Integer getMonthlyPageViewsEntitlement() {
        return this.MonthlyPageViewsEntitlement;
    }

    @JsonProperty("MonthlyPageViewsEntitlement")
    public void setMonthlyPageViewsEntitlement(Integer MonthlyPageViewsEntitlement) {
        this.MonthlyPageViewsEntitlement = MonthlyPageViewsEntitlement;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Organization ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("Name", "Name", "string", "xsd:string", 80, false, false, true, false, false, false, true);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("Division", "Division", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("Street", "Street", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("State", "State/Province", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("PostalCode", "Zip/Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("Latitude", "Latitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("Longitude", "Longitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("Address", "Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("Phone", "Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("Fax", "Fax", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("PrimaryContact", "Primary Contact", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("DefaultLocaleSidKey", "Locale", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("LanguageLocaleKey", "Language", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("ReceivesInfoEmails", "Info Emails", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("ReceivesAdminInfoEmails", "Info Emails Admin", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("PreferencesRequireOpportunityProducts", "RequireOpportunityProducts", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("PreferencesTransactionSecurityPolicy", "TransactionSecurityPolicy", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("PreferencesTerminateOldestSession", "TerminateOldestSession", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("FiscalYearStartMonth", "Fiscal Year Starts In", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("UsesStartDateAsFiscalYearName", "Fiscal Year Name by Start", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("DefaultAccountAccess", "Default Account Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("DefaultContactAccess", "Default Contact Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("DefaultOpportunityAccess", "Default Opportunity Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("DefaultLeadAccess", "Default Lead Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("DefaultCaseAccess", "Default Case Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("DefaultCalendarAccess", "Default Calendar Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("DefaultPricebookAccess", "Default Price Book Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("DefaultCampaignAccess", "Default Campaign Access", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("ComplianceBccEmail", "Compliance BCC Email", "email", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("UiSkin", "UI Skin", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("SignupCountryIsoCode", "Signup Country", "string", "xsd:string", 2, false, true, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("TrialExpirationDate", "Trial Expiration Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("OrganizationType", "Edition", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("InstanceName", "Instance Name", "string", "xsd:string", 5, false, true, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("IsSandbox", "Is Sandbox", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("WebToCaseDefaultOrigin", "Web to Cases Default Origin", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("MonthlyPageViewsUsed", "Monthly Page Views Used", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("MonthlyPageViewsEntitlement", "Monthly Page Views Allowed", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField46);

        description.setLabelPlural("Organizations");
        description.setLabel("Organization");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/Organization/describe");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/Organization");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/Organization/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("Organization");

        return description;
    }
}
