/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DefaultPricebookAccess
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Organization_DefaultPricebookAccessEnum {

    // None
    NONE("None"),
    // Read
    READ("Read"),
    // ReadSelect
    READSELECT("ReadSelect");

    final String value;

    private Organization_DefaultPricebookAccessEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Organization_DefaultPricebookAccessEnum fromValue(String value) {
        for (Organization_DefaultPricebookAccessEnum e : Organization_DefaultPricebookAccessEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
