/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist SobjectType
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum RecordType_SobjectTypeEnum {

    // Account
    ACCOUNT("Account"),
    // Announcement
    ANNOUNCEMENT("Announcement"),
    // Asset
    ASSET("Asset"),
    // AssetRelationship
    ASSETRELATIONSHIP("AssetRelationship"),
    // AssistantProgress
    ASSISTANTPROGRESS("AssistantProgress"),
    // Campaign
    CAMPAIGN("Campaign"),
    // CampaignMember
    CAMPAIGNMEMBER("CampaignMember"),
    // Case
    CASE("Case"),
    // CollaborationGroupRank
    COLLABORATIONGROUPRANK("CollaborationGroupRank"),
    // CollaborationGroupRecord
    COLLABORATIONGROUPRECORD("CollaborationGroupRecord"),
    // ComponentResponseCache
    COMPONENTRESPONSECACHE("ComponentResponseCache"),
    // Contact
    CONTACT("Contact"),
    // ContentVersion
    CONTENTVERSION("ContentVersion"),
    // Contract
    CONTRACT("Contract"),
    // CustomSettingNameIndex
    CUSTOMSETTINGNAMEINDEX("CustomSettingNameIndex"),
    // DuplicateErrorLog
    DUPLICATEERRORLOG("DuplicateErrorLog"),
    // DuplicateRecordItem
    DUPLICATERECORDITEM("DuplicateRecordItem"),
    // DuplicateRecordSet
    DUPLICATERECORDSET("DuplicateRecordSet"),
    // Event
    EVENT("Event"),
    // FileInspectionResult
    FILEINSPECTIONRESULT("FileInspectionResult"),
    // FileSearchActivity
    FILESEARCHACTIVITY("FileSearchActivity"),
    // FlowRecordRelation
    FLOWRECORDRELATION("FlowRecordRelation"),
    // FlowStageRelation
    FLOWSTAGERELATION("FlowStageRelation"),
    // Goal
    GOAL("Goal"),
    // GoalLink
    GOALLINK("GoalLink"),
    // Idea
    IDEA("Idea"),
    // InboundSocialPost
    INBOUNDSOCIALPOST("InboundSocialPost"),
    // Lead
    LEAD("Lead"),
    // ListEmail
    LISTEMAIL("ListEmail"),
    // ListEmailRecipientSource
    LISTEMAILRECIPIENTSOURCE("ListEmailRecipientSource"),
    // ListEmailSentResult
    LISTEMAILSENTRESULT("ListEmailSentResult"),
    // Macro
    MACRO("Macro"),
    // MacroAction
    MACROACTION("MacroAction"),
    // MacroInstruction
    MACROINSTRUCTION("MacroInstruction"),
    // ManagedContentBlock
    MANAGEDCONTENTBLOCK("ManagedContentBlock"),
    // ManagedContentBlockVersion
    MANAGEDCONTENTBLOCKVERSION("ManagedContentBlockVersion"),
    // Metric
    METRIC("Metric"),
    // MetricDataLink
    METRICDATALINK("MetricDataLink"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // Order
    ORDER("Order"),
    // OrgDeleteRequest
    ORGDELETEREQUEST("OrgDeleteRequest"),
    // PersonalizationResource
    PERSONALIZATIONRESOURCE("PersonalizationResource"),
    // Pricebook2
    PRICEBOOK2("Pricebook2"),
    // Product2
    PRODUCT2("Product2"),
    // QuickText
    QUICKTEXT("QuickText"),
    // RecordAction
    RECORDACTION("RecordAction"),
    // RecordOrigin
    RECORDORIGIN("RecordOrigin"),
    // RequestsForAccessSIQ
    REQUESTSFORACCESSSIQ("RequestsForAccessSIQ"),
    // Scorecard
    SCORECARD("Scorecard"),
    // ScorecardAssociation
    SCORECARDASSOCIATION("ScorecardAssociation"),
    // ScorecardMetric
    SCORECARDMETRIC("ScorecardMetric"),
    // SearchActivity
    SEARCHACTIVITY("SearchActivity"),
    // SearchPromotionRule
    SEARCHPROMOTIONRULE("SearchPromotionRule"),
    // SetupAssistantAnswer
    SETUPASSISTANTANSWER("SetupAssistantAnswer"),
    // SetupAssistantProgress
    SETUPASSISTANTPROGRESS("SetupAssistantProgress"),
    // SetupFlowProgress
    SETUPFLOWPROGRESS("SetupFlowProgress"),
    // SiqUserBlacklist
    SIQUSERBLACKLIST("SiqUserBlacklist"),
    // Solution
    SOLUTION("Solution"),
    // StreamActivityAccess
    STREAMACTIVITYACCESS("StreamActivityAccess"),
    // SyncTransactionLog
    SYNCTRANSACTIONLOG("SyncTransactionLog"),
    // Task
    TASK("Task"),
    // TransactionSecurityAction
    TRANSACTIONSECURITYACTION("TransactionSecurityAction"),
    // TransactionSecurityActionEvent
    TRANSACTIONSECURITYACTIONEVENT("TransactionSecurityActionEvent"),
    // UserMetrics
    USERMETRICS("UserMetrics"),
    // UserNavItem
    USERNAVITEM("UserNavItem"),
    // WorkCoaching
    WORKCOACHING("WorkCoaching"),
    // WorkFeedback
    WORKFEEDBACK("WorkFeedback"),
    // WorkFeedbackQuestion
    WORKFEEDBACKQUESTION("WorkFeedbackQuestion"),
    // WorkFeedbackQuestionSet
    WORKFEEDBACKQUESTIONSET("WorkFeedbackQuestionSet"),
    // WorkFeedbackRequest
    WORKFEEDBACKREQUEST("WorkFeedbackRequest"),
    // WorkFeedbackTemplate
    WORKFEEDBACKTEMPLATE("WorkFeedbackTemplate"),
    // WorkPerformanceCycle
    WORKPERFORMANCECYCLE("WorkPerformanceCycle");

    final String value;

    private RecordType_SobjectTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RecordType_SobjectTypeEnum fromValue(String value) {
        for (RecordType_SobjectTypeEnum e : RecordType_SobjectTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
