/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LastViewedChart
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum UserListView_LastViewedChartEnum {

    // AccountsByIndustry
    ACCOUNTSBYINDUSTRY("AccountsByIndustry"),
    // CampaignsByNumberOfResponses
    CAMPAIGNSBYNUMBEROFRESPONSES("CampaignsByNumberOfResponses"),
    // CampaignsByStatus
    CAMPAIGNSBYSTATUS("CampaignsByStatus"),
    // CampaignsByType
    CAMPAIGNSBYTYPE("CampaignsByType"),
    // ContactsByAccount
    CONTACTSBYACCOUNT("ContactsByAccount"),
    // ContactsByLeadSource
    CONTACTSBYLEADSOURCE("ContactsByLeadSource"),
    // LeadsBySource
    LEADSBYSOURCE("LeadsBySource"),
    // PipelineByAccount
    PIPELINEBYACCOUNT("PipelineByAccount"),
    // PipelineByFiscalPeriod
    PIPELINEBYFISCALPERIOD("PipelineByFiscalPeriod"),
    // PipelineByStage
    PIPELINEBYSTAGE("PipelineByStage");

    final String value;

    private UserListView_LastViewedChartEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserListView_LastViewedChartEnum fromValue(String value) {
        for (UserListView_LastViewedChartEnum e : UserListView_LastViewedChartEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
