/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Sep 06 16:51:28 IST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Preference
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum UserPreference_PreferenceEnum {

    // 100
    _100("100"),
    // 101
    _101("101"),
    // 102
    _102("102"),
    // 57
    _57("57"),
    // 58
    _58("58"),
    // 91
    _91("91"),
    // 92
    _92("92"),
    // 93
    _93("93"),
    // 94
    _94("94"),
    // 96
    _96("96"),
    // 97
    _97("97"),
    // 98
    _98("98"),
    // 99
    _99("99");

    final String value;

    private UserPreference_PreferenceEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserPreference_PreferenceEnum fromValue(String value) {
        for (UserPreference_PreferenceEnum e : UserPreference_PreferenceEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
